
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/auth-service
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        ddl-auto:
    generate-ddl: true
