
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task-service
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        ddl-auto:
    generate-ddl: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8089/eureka
  instance:
    preferIpAddress: true
